/**
 * Created by cykj-hgc on 2016/11/18.
 */

exports.products = [
    {
        id: '1',
        model: 'allianz',
        title: '安联臻爱医疗保险',
        des: '平民价百万医疗险',
        company: '安联保险',
        price: '152~12525',
        hadSell: 26,
        bigLogo: require('../assets/images/products/1/logo_big.jpg'),
        smallLogo: require('../assets/images/products/1/logo_small.jpg'),
        buyLink: '',
        picNum: 6,
        typeOf: 'health',
    },
    {
        id: '2',
        model: 'allianz',
        title: '安联个人意外保障计划',
        des: '百万保额，全年365天保障',
        company: '安联保险',
        price: '450~4800',
        hadSell: 16,
        bigLogo: require('../assets/images/products/2/logo_big.jpg'),
        smallLogo: require('../assets/images/products/2/logo_small.jpg'),
        buyLink: '',
        picNum: 5,
        typeOf: 'accident',
    },
    {
        id: '3',
        model: 'allianz',
        title: '居无忧家庭财产保障计划',
        des: '安联家财险 全面的财产保障专家',
        company: '安联保险',
        price: '350~950',
        hadSell: 20,
        bigLogo: require('../assets/images/products/3/logo_big.jpg'),
        smallLogo: require('../assets/images/products/3/logo_small.jpg'),
        buyLink: '',
        picNum: 5,
        typeOf: 'property',
    },
    {
        id: '4',
        model: 'allianz',
        title: '安联户外运动保障计划',
        des: '安联家财险 全面的财产保障专家',
        company: '安联保险',
        price: '5~600',
        hadSell: 28,
        bigLogo: require('../assets/images/products/4/logo_big.jpg'),
        smallLogo: require('../assets/images/products/4/logo_small.jpg'),
        buyLink: '',
        picNum: 5,
        typeOf: 'accident',
    },
    {
        id: '5',
        model: 'allianz',
        title: '安联商旅计划-新版',
        des: '携带一份保障上路',
        company: '安联保险',
        price: '16~3720',
        hadSell: 32,
        bigLogo: require('../assets/images/products/5/logo_big.jpg'),
        smallLogo: require('../assets/images/products/5/logo_small.jpg'),
        buyLink: '',
        picNum: 4,
        typeOf: 'tourism',
    },
    {
        id: '6',
        model: 'allianz',
        title: '乐享人生-安联个人保障计划（成人版）',
        des: '意外健康综合保障，一张保单多角度保障！',
        company: '安联保险',
        price: '410~2580',
        hadSell: 18,
        bigLogo: require('../assets/images/products/6/logo_big.jpg'),
        smallLogo: require('../assets/images/products/6/logo_small.jpg'),
        buyLink: '',
        picNum: 4,
        typeOf: 'health',
    },
    {
        id: '7',
        model: 'allianz',
        title: '乐享人生-安联个人保障计划（少儿幼儿标准版）',
        des: '少儿专属，孩子们的守护天使',
        company: '安联保险',
        price: '190~350',
        hadSell: 20,
        bigLogo: require('../assets/images/products/7/logo_big.jpg'),
        smallLogo: require('../assets/images/products/7/logo_small.jpg'),
        buyLink: '',
        picNum: 4,
        typeOf: 'health',
    },
    {
        id: '8',
        model: 'allianz',
        title: '乐享人生-安联个人保障计划（女性版）',
        des: '女性专属',
        company: '安联保险',
        price: '320~2180',
        hadSell: 11,
        bigLogo: require('../assets/images/products/8/logo_big.jpg'),
        smallLogo: require('../assets/images/products/8/logo_small.jpg'),
        buyLink: '',
        picNum: 4,
        typeOf: 'health',
    },
    {
        id: '9',
        model: 'allianz',
        title: '环游四海（新版）',
        des: '安联全球旅行保障计划',
        company: '安联保险',
        price: '40~5300',
        hadSell: 11,
        bigLogo: require('../assets/images/products/9/logo_big.jpg'),
        smallLogo: require('../assets/images/products/9/logo_small.jpg'),
        buyLink: '',
        picNum: 4,
        typeOf: 'tourism',
    },
    {
        id: '10',
        model: 'allianz',
        title: '抗癌卫士',
        des: '患癌也能买',
        company: '中国平安',
        price: '46.5起',
        hadSell: 11,
        bigLogo: require('../assets/images/products/10/logo_big.jpg'),
        smallLogo: require('../assets/images/products/10/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/insmall/p/ins.do?c=BTBXDL&sc=00&source=&p=H751&appColumn=&eid=&mcid=',
        picNum: 3,
        typeOf: 'health',
    },
    {
        id: '11',
        model: 'allianz',
        title: '母婴卫士',
        des: '既保母亲又保孩子',
        company: '中国平安',
        price: '5~35',
        hadSell: 9,
        bigLogo: require('../assets/images/products/11/logo_big.jpg'),
        smallLogo: require('../assets/images/products/11/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/insmall/p/ins.do?c=BTBXDL&sc=00&source=&p=H752&appColumn=&eid=&mcid=',
        picNum: 1,
        typeOf: 'health',
    },
    {
        id: '12',
        model: 'allianz',
        title: '平安e家保',
        des: '一家人的医疗保险',
        company: '中国平安',
        price: '199起',
        hadSell: 9,
        bigLogo: require('../assets/images/products/12/logo_big.jpg'),
        smallLogo: require('../assets/images/products/12/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ins-h5/H017H018/insurance.do?channel=BTBXDL&salesCode=00&source=&appColumn=&eid=&mcid=#insure',
        picNum: 1,
        typeOf: 'health',
    },
    {
        id: '13',
        model: 'allianz',
        title: '运动卫士',
        des: '平安个人综合意外伤害保险条款',
        company: '中国平安',
        price: '58~382',
        hadSell: 13,
        bigLogo: require('../assets/images/products/13/logo_big.jpg'),
        smallLogo: require('../assets/images/products/13/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ins-h5/insurance/#/insurance?c=BTBXDL&g=A000000004&sc=00',
        picNum: 1,
        typeOf: 'accident',
    },
    {
        id: '14',
        model: 'allianz',
        title: '安全保',
        des: '安全+全面=一份你期待已久的保障',
        company: '中国平安',
        price: '92~561',
        hadSell: 23,
        bigLogo: require('../assets/images/products/14/logo_big.jpg'),
        smallLogo: require('../assets/images/products/14/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ins-h5/insurance/#/insurance?c=BTBXDL&g=A000000005&sc=00',
        picNum: 3,
        typeOf: 'health',
    },
    {
        id: '15',
        model: 'allianz',
        title: '抗癌卫士（海外版）',
        des: '首款可去海外就医的互联网抗癌险',
        company: '中国平安',
        price: '398~3410',
        hadSell: 3,
        bigLogo: require('../assets/images/products/15/logo_big.jpg'),
        smallLogo: require('../assets/images/products/15/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ehis-hm/H753/insurance.do?c=BTBXDL&sc=00&g=A000000007&source=&extra.appColumn=&extra.eid=&extra.mcid=',
        picNum: 3,
        typeOf: 'health',
    },
    {
        id: '16',
        model: 'allianz',
        title: 'e生保',
        des: '让每个人轻松拥有一份百万医疗保障',
        company: '中国平安',
        price: '231起',
        hadSell: 5,
        bigLogo: require('../assets/images/products/16/logo_big.jpg'),
        smallLogo: require('../assets/images/products/16/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ehis-hm/H704/purchaseNow.do?c=BTBXDL&sc=00&source=&extra.appColumn=&extra.eid=&extra.mcid=',
        picNum: 4,
        typeOf: 'health',
    },
    {
        id: '17',
        model: 'allianz',
        title: '重大疾病海外保',
        des: '出国看病全无忧',
        company: '中国平安',
        price: '490起',
        hadSell: 5,
        bigLogo: require('../assets/images/products/17/logo_big.jpg'),
        smallLogo: require('../assets/images/products/17/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ehis-hm/H753/insurance.do?c=BTBXDL&sc=00&g=A000000008&source=&extra.appColumn=&extra.eid=&extra.mcid=',
        picNum: 4,
        typeOf: 'health',
    },
    {
        id: '18',
        model: 'allianz',
        title: '重大疾病海外保vip',
        des: '出国看病全无忧',
        company: '中国平安',
        price: '922~8352',
        hadSell: 9,
        bigLogo: require('../assets/images/products/18/logo_big.jpg'),
        smallLogo: require('../assets/images/products/18/logo_small.jpg'),
        buyLink: 'http://mobile.health.pingan.com/ehis-hm/H753/insurance.do?c=BTBXDL&sc=00&g=A000000009&source=&extra.appColumn=&extra.eid=&extra.mcid=',
        picNum: 4,
        typeOf: 'health',
    },
];